# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI - deploy using github actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js #${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20 #${{ matrix.node-version }}
       #cache: 'npm'
    #- run: npm ci
    - name: building frontend
      run: | 
#cd /D:/Jolly/myreactapp/myreactapp/WWA-frontend-master
        cd */WWA-frontend-master
        rm -rf node_modules
        npm install
      #sudo npm run test
       
    #- run: npm test

    #- name: Deploy 🚀
      #uses: JamesIves/github-pages-deploy-action@v4
      #with:
        #folder: build # The folder the action should deploy.
