name: Snyk Security Scanse

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Authenticate with Snyk
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Install dependencies
        run: npm install  

      - name: Run Snyk security test
        run: snyk test --all-projects --json > snyk-report.json
        # run: snyk test --all-projects --json
        # run: snyk test --all-projects --json || true > snyk-report.json
        
       # - name: Upload Snyk test results as an artifact
       #   uses: actions/upload-artifact@v2
        #  with:
         #   name: snyk-report
         #   path: snyk-report.json
    
      - name: Upload Snyk test results as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: Snyk-report
         
          path: |
            report_html.html
            snyk-report.json
      #  - name: Display Snyk test results
       #   run: cat snyk-report.json

    

      # Optionally, you can fail the workflow if vulnerabilities are found
      #- name: Fail workflow on vulnerabilities
      #  run: snyk test --all-projects --severity-threshold=high
      #  continue-on-error: true

      #- name: Fail workflow if vulnerabilities found
      #  run: exit 1
      #  if: ${{ failure() }}

    
