name: "jest_scan_github_actions"
on:
  push:
    branches:
      - main
      
jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies and run tests
        run: |
          npm install
          npm test -- --coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jollyjerinjoy
            -Dsonar.projectKey=myreactapp
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

            