name: test test Node.js CI with SonarClouds
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test with SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Set this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm run test # Make sure this script generates coverage reports

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=myreactapp
          -Dsonar.organization=jollyjerinjoy
          -Dsonar.sources=src
          -Dsonar.tests=test
          -Dsonar.test.inclusions=**/*.spec.js,**/*.test.js
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
